meta_title: "Bahia Blanca Artisanat - Jeune marque éthique"
meta_description: "Bahia Blanca, jeune marque de mode éthique qui place les savoir-faire d'ethnies du Mexique au coeur de ses créations."
meta_image: "small_card.jpg" # Une image dans votre dossier app/assets/images/

